### ISSUE TITLE
Combobox display only first 25 Projects

### ISSUE THREAD

**Issue by TTonNguyen** [raidensan/RedMineIssueCreator#3] opened 2017-12-21 14:25 UTC
Hi,
thank you for the Plugin. I can install and connect to our Redmine Server. But when i tried to creat a Issues from context menu. But the Create Issues From cannot load all Project that we had, only the first 25 Project. Can you please fix this error ? Search in the project box is pretty cool to have.

**Comment by raidensan** [comment] 2017-12-21 16:23
Hi,
Thanks for using the plugin I hope it serves you well.
About the issue, there is no limitation mechanism coded in the plugin nor in the API. I will try to reproduce this issue but I am guessing it has something to do with permissions.

Also I will look into implementing search in Project box. Thanks for your feedback, greatly appreciated.

**Comment by raidensan** [comment] 2018-11-14 11:24
Finally managed to inspect this issue. Unfortunately I couldn't reproduce the issue, hence closing the issue. 

I would happily re-inspect and try to resolve if there is a way to re-produce this.

**Closed as completed by raidensan** 2018-11-14 11:24 UTC
